### ISSUE TITLE
2 month sample is from 2023

### ISSUE THREAD

**Issue by karann-msft** [af/hyperpaper-planner#17]
Hi, I am getting the scribe as a valentine's gift for my wife and she is really into daily planner. This is supposed to be a replacement and I'd like her to try hyperpaper. The two month trial is from last year. I'd appreciate a trial for Feb, March or March, April.

**Comment by af** [comment]
Hi, shoot an email to orders@hyperpaper.me and I'll get you a better trial pdf :)
