### ISSUE TITLE
Usage Comments

### ISSUE THREAD

**Issue by tk-47** [af/hyperpaper-planner#5]
I have been using and playing with this on the Remarkable 2.  This is the cleanest of all of the (many) planners I have tested.  Some of my comments here may already be something you plan to do or change, just listing what I see:
- Dots need to be lines for mainstream use. I am not a huge fan of the dots even though it is a clean look. People will expect lines.
- For a year of planning, it will need more pages of notes and projects
- All of the hyperlinks are fast and worked. I found no dead links.
- The overall design is the best I have seen. Most are just too busy or try to do too much stylistically and the file gets big and navigation gets complicated.  Very nice design.
- You may want to consider a margin for the Remarkable 2 toolbar.  I have seen complaints in R2 forums and on product reviews when you have to close the toolbar to access the full content. I see that issue both ways, so it is more of an observation than anything.

I look forward to seeing this develop into a finished product...hopefully for 2022.

**Comment by af** [comment]
Thanks for the kind words and great feedback 🙏 

* dots vs lines: I prefer dots personally, but I think this should be fairly easy to make configurable.
* notes/project pages: agreed, I've started on adding support for more of these already, should be no problem
* links working: glad to hear 👍 I have definitely dealt with a few broken links while working on this, haha!
* design: Thank you! I definitely want to keep it simple and clean. Glad to hear somebody else appreciates a small filesize too, I've been keeping an eye on that as I go
* left margin: I thought about this before, reason I didn't make space for it is that I almost always have the toolbar collapsed. Will play with adding this, but also don't want to sacrifice the precious page real estate

**Comment by tk-47** [comment]
I hesitated to even mention the margin because the spacing, especially on the yearly calendar, is the best I have seen.  Please let me know when the 2022 is available for download and/or purchase.

This is great work and this type of clean design is needed in the R2 world.

**Comment by jmlgo** [comment]
best I have seen so far. waiting for the 2022 update!

**Comment by jmlgo** [comment]
One suggestion: gray lines look too clear on the remarkable. A bit darker lines would improve the experience.

**Comment by af** [comment]
Forgot about this issue! All of these suggestions have now been addressed, thanks again for the early feedback :)
